#!/usr/bin/env python3
"""
NakostatBoiler - Generate Secrets Script
Fetches IoT certificates and WiFi credentials from AWS SSM Parameter Store
and generates the secrets.h file.
"""

import os
import sys
from pathlib import Path
import boto3
from botocore.exceptions import ClientError

# Configuration
# Boiler firmware connects as the nakostat ESP32 Thing for the chosen env.
# The nakostat IotStack provisions the Thing/cert/policy and stores the
# cert + private key in SSM under /nakostat/{env}/esp32/...
PROJECT_NAME = "NakostatBoiler"
NAKOSTAT_ENV = os.environ.get('NAKOSTAT_ENV', 'sandbox')
THING_NAME = f"nakostat-esp32-{NAKOSTAT_ENV}"
SSM_PREFIX = f"/nakostat/{NAKOSTAT_ENV}/esp32"
TOPIC_PREFIX = f"nakostat/{NAKOSTAT_ENV}/esp32"

# WiFi credentials are stored at a common location
WIFI_SSM_PREFIX = "/Nakomis/Wifi"


def get_ssm_parameter(ssm_client, name: str, decrypt: bool = True) -> str:
    """Fetch a parameter from SSM Parameter Store."""
    try:
        response = ssm_client.get_parameter(Name=name, WithDecryption=decrypt)
        return response['Parameter']['Value']
    except ClientError as e:
        if e.response['Error']['Code'] == 'ParameterNotFound':
            return None
        raise


def get_iot_endpoints(iot_client) -> tuple:
    """Get IoT data and credentials endpoints."""
    # Data endpoint
    data_response = iot_client.describe_endpoint(endpointType='iot:Data-ATS')
    data_endpoint = data_response['endpointAddress']

    # Credentials endpoint
    creds_response = iot_client.describe_endpoint(endpointType='iot:CredentialProvider')
    creds_endpoint = creds_response['endpointAddress']

    return data_endpoint, creds_endpoint


def generate_secrets_h(
    cert_pem: str,
    private_key: str,
    ca_cert: str,
    wifi_ssid: str,
    wifi_password: str,
    iot_endpoint: str,
    credentials_endpoint: str
) -> str:
    """Generate the contents of secrets.h"""

    return f'''/**
 * secrets.h - WiFi and AWS IoT credentials
 *
 * AUTO-GENERATED by generate_secrets.py
 * DO NOT COMMIT THIS FILE TO GIT!
 *
 * Regenerate by running:
 *   python scripts/generate_secrets.py
 */

#ifndef SECRETS_H
#define SECRETS_H

// WiFi credentials (can also be set via BLE)
#define WIFI_SSID "{wifi_ssid}"
#define WIFI_PASSWORD "{wifi_password}"

// AWS IoT endpoint
#define AWS_IOT_ENDPOINT "{iot_endpoint}"

// AWS IoT credentials provider endpoint
#define AWS_CREDENTIALS_ENDPOINT "{credentials_endpoint}"

// IoT Thing name (used as MQTT client id)
#define AWS_IOT_THING_NAME "{THING_NAME}"

// MQTT topic prefix for this device. Command topic = TOPIC_PREFIX/command,
// status topic = TOPIC_PREFIX/status.
#define MQTT_TOPIC_PREFIX "{TOPIC_PREFIX}"
#define MQTT_COMMAND_TOPIC MQTT_TOPIC_PREFIX "/command"
#define MQTT_STATUS_TOPIC  MQTT_TOPIC_PREFIX "/status"

// Fleet env this firmware was provisioned for
#define NAKOSTAT_ENV "{NAKOSTAT_ENV}"

// Role alias for credentials provider (unused for direct MQTT auth, kept for OTA flows)
#define AWS_IOT_ROLE_ALIAS "{PROJECT_NAME}RoleAlias"

// Certificate (PEM format)
static const char AWS_CERT_CRT[] PROGMEM = R"EOF(
{cert_pem})EOF";

// Private key (PEM format)
static const char AWS_CERT_PRIVATE[] PROGMEM = R"EOF(
{private_key})EOF";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
{ca_cert})EOF";

#endif // SECRETS_H
'''


def main():
    print("=" * 60)
    print(f"  {PROJECT_NAME} - Generate Secrets")
    print("=" * 60)
    print()

    # Check AWS profile
    aws_profile = os.environ.get('AWS_PROFILE')
    if not aws_profile:
        print("Warning: AWS_PROFILE not set")
        aws_profile = input("Enter AWS profile name: ").strip()
        if not aws_profile:
            print("No profile provided. Exiting.")
            sys.exit(1)
        os.environ['AWS_PROFILE'] = aws_profile

    print(f"AWS Profile: {aws_profile}")
    print()

    # Initialize AWS clients
    session = boto3.Session()
    ssm_client = session.client('ssm')
    iot_client = session.client('iot')

    # Fetch certificate and private key from SSM
    print("Fetching IoT credentials from SSM...")
    cert_pem = get_ssm_parameter(ssm_client, f"{SSM_PREFIX}/certPem")
    private_key = get_ssm_parameter(ssm_client, f"{SSM_PREFIX}/privKey")

    if not cert_pem or not private_key:
        print(f"Error: Could not find IoT credentials in SSM")
        print(f"  Expected: {SSM_PREFIX}/certPem")
        print(f"  Expected: {SSM_PREFIX}/privKey")
        print()
        print("Have you deployed the CDK stack?")
        print("  cd infra && cdk deploy")
        sys.exit(1)

    print("  Certificate: OK")
    print("  Private Key: OK")

    # Fetch WiFi credentials (optional)
    print()
    print("Fetching WiFi credentials from SSM...")
    wifi_ssid = get_ssm_parameter(ssm_client, f"{WIFI_SSM_PREFIX}/SSID")
    wifi_password = get_ssm_parameter(ssm_client, f"{WIFI_SSM_PREFIX}/Password")

    if wifi_ssid and wifi_password:
        print(f"  SSID: {wifi_ssid}")
        print("  Password: OK")
    else:
        print("  WiFi credentials not found (can be configured via BLE)")
        wifi_ssid = ""
        wifi_password = ""

    # Get IoT endpoints
    print()
    print("Fetching IoT endpoints...")
    iot_endpoint, credentials_endpoint = get_iot_endpoints(iot_client)
    print(f"  IoT Endpoint: {iot_endpoint}")
    print(f"  Credentials Endpoint: {credentials_endpoint}")

    # Read Amazon Root CA
    print()
    print("Reading Amazon Root CA...")
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    ca_file = project_root / "AmazonRootCA1.pem"

    if ca_file.exists():
        ca_cert = ca_file.read_text().strip()
        print("  Root CA: OK")
    else:
        print(f"  Warning: {ca_file} not found, using embedded CA")
        # Embedded Amazon Root CA 1
        ca_cert = """-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----"""

    # Generate secrets.h
    print()
    print("Generating secrets.h...")
    secrets_content = generate_secrets_h(
        cert_pem=cert_pem,
        private_key=private_key,
        ca_cert=ca_cert,
        wifi_ssid=wifi_ssid,
        wifi_password=wifi_password,
        iot_endpoint=iot_endpoint,
        credentials_endpoint=credentials_endpoint
    )

    secrets_file = project_root / "include" / "secrets.h"
    secrets_file.write_text(secrets_content)

    print(f"  Written: {secrets_file}")
    print()
    print("=" * 60)
    print("  Secrets generated successfully!")
    print("=" * 60)
    print()
    print("IMPORTANT: Do not commit secrets.h to git!")
    print("The .gitignore should already exclude it.")


if __name__ == "__main__":
    main()
